services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:8080"
    volumes:
      - ./:${APP_PATH}
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - medarea-network
    depends_on:
      - php

  php:
    build:
      args:
        gid: ${GID}
        uid: ${UID}
        xdebug_idekey: ${XDEBUG_IDEKEY}
        xdebug_client_port: ${XDEBUG_CLIENT_PORT}
        target: dev
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:/var/www/app
      - ./docker/php/config/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - medarea-network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - db-data:/var/lib/postgres
      - ./docker/postgres/config/postgres.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - medarea-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 10s
      retries: 10

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:8.2.0-alpine
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  scheduler:
    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: scheduler
    volumes:
      - ./:${APP_PATH}
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/config/php-fpm.conf:/usr/local/etc/php-fpm-dev.d/www.conf
    restart: on-failure
    depends_on:
      - php

  worker:
    container_name: ${COMPOSE_PROJECT_NAME}-worker
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/php/Dockerfile
      target: worker
    volumes:
      - ./:${APP_PATH}
      - ./docker/php/config/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/config/php-fpm.conf:/usr/local/etc/php-fpm-dev.d/www.conf
    restart: on-failure
    depends_on:
      - php

volumes:
  db-data:
  redis-data:

networks:
  medarea-network:
    driver: bridge